NARKOZ/gitlab

- lib/gitlab/client.rb
- lib/gitlab/client/repository_files.rb
- spec/fixtures/repository_file.json
- spec/gitlab/client/repository_files_spec.rb
The original doc is at http://doc.gitlab.com/ce/api/repository_files.html.
I didn't implement the GET as the functionality is already present, albeit in a different module. Let me know if it should be added anyway.
Cheers.
> Added support for repository files create, edit and remove.

- lib/gitlab/client/projects.rb
There is currently no way to search for a project, add a project_search method based on gitlab's /project/search API
> Add project_search method

- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
JSON.parse converts "true" to a boolean, but the custom parsing function
just checks if the body is an array or hash.
So check if the body is a real boolean and if it's true, return an
empty hash.
This is with gitlab 7.11.4, didn't check any other versions...
> deleting a gitlab project returns the string "true"

- lib/gitlab/client/groups.rb
- spec/fixtures/group_create_with_description.json
- spec/gitlab/client/groups_spec.rb
In the description of the method ```create_group``` indicated that the parameter ```description``` supported, but the method signature does not support it.
> Added support description option in create_group method

- lib/gitlab/error.rb
- lib/gitlab/request.rb
For example when you create a merge request with the same source and target branch you got_
_You can not use same project/branch for source and target_
and status 422.
> Add Unprocessable error handler

- README.md
- lib/gitlab/cli.rb
- lib/gitlab/cli_helpers.rb
- spec/gitlab/cli_spec.rb
Adding a `--json` parameter to a CLI command returns the output in JSON. Example:
````
gitlab project 605 --json
>>>> {
"cmd": "Gitlab.project 605",
"result": {
"archived": false,
"avatar_url": null,
"created_at": "2015-05-21T13:50:16.514Z",
"default_branch": "master",
"description": "",
...
}
}
````
For "single row" returned by the command, the `result` field will be a map. If there are multiple rows returned, the `result`field will be an array of maps.
You are then able to do things like this (given you have [jq](http://stedolan.github.io/jq/) installed on your system):
````
gitlab project PROJECT_ID --json | jq '.result.id'
>>>> PROJECT_ID
````
The JSON is pretty-printed to make it readable for humans :-)
> Add a `--json` parameter to the CLI commands

- lib/gitlab/client.rb
- lib/gitlab/client/namespaces.rb
- spec/fixtures/namespaces.json
- spec/gitlab/client/namespaces_spec.rb
I'd like to have support for the `/namespaces` [endpoint](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/namespaces.md), especially in the context of using gitlab-ee. Usage supports `:per_page`, `:page`, and `:search` options. 
**Examples:**
```ruby
Gitlab.namespaces
Gitlab.namespaces(per_page: 5, page: 2)
Gitlab.namespaces(search: 'foobar')
```
Tests have been included.
> Add support for namespaces endpoint

- lib/gitlab/help.rb
We now render each `@option` value on a separate line for
better readability.
This is a PoC example - still need to write a spec for this.
`rake && exe/gitlab help create_project`
Before:
```
= Gitlab::Client::Projects.create_project
(from gem gitlab-3.4.0)
=== Implementation from Projects
------------------------------------------------------------------------------
create_project name options={}
------------------------------------------------------------------------------
Creates a new project.
@example
gitlab create_project 'gitlab'
gitlab create_project 'viking' :description => 'Awesome project'
gitlab create_project 'Red' :wall_enabled => false
@param  [String] name The name of a project. @param  [Hash] options A
customizable set of options. @option options [String] :description The …
```
> Improved parameter description in help output.

- lib/gitlab.rb
- lib/gitlab/objectified_hash.rb
- lib/gitlab/paginated_response.rb
See https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding
Prior, I was unable to mock the client, for example by doing:
```ruby
expect(Gitlab).to receive(:protect_branch).with(anything(), anything())
```
> Use `respond_to_missing?` instead of `respond_to?`

- lib/gitlab/client/groups.rb
- spec/fixtures/group_member_edit.json
- spec/gitlab/client/groups_spec.rb
This pull request add the missing method edit_group_member to the groups client.
> Add method edit_group_member

- lib/gitlab/client/groups.rb
- spec/fixtures/group_projects.json
- spec/gitlab/client/groups_spec.rb
- spec/gitlab/shell_spec.rb
This allows the user to get a list of projects under a specific group.
> Add API to get a list of projects under a group

- spec/gitlab/client/groups_spec.rb
I sort of noticed this tonight, apologies for not noticing it in the previous PR.
> Move delete_group spec out of the create_group spec

- lib/gitlab/client.rb
- lib/gitlab/client/build_triggers.rb
- lib/gitlab/client/build_variables.rb
- lib/gitlab/client/builds.rb
- spec/fixtures/build_erase.json
- spec/fixtures/trigger.json
- spec/fixtures/triggers.json
- spec/fixtures/variable.json
- spec/fixtures/variables.json
- spec/gitlab/client/build_triggers_spec.rb
- spec/gitlab/client/build_variables_spec.rb
- spec/gitlab/client/builds_spec.rb
This client was missing APIs for various new CI features such as:
* Build triggers
* Build variables
* Build content erasing
Also missing is (artifact download)[https://gitlab.com/help/api/builds.md#get-build-artifacts], but I don't know how to go about returning the binary zipfile content.
> Add missing Build APIs

- lib/gitlab/error.rb
- lib/gitlab/request.rb
- spec/gitlab/error_spec.rb
- spec/gitlab/request_spec.rb
Gitlab subclasses errors depending on the response status.
This is great because it allows consumers to handle specific
errors properly.
It is not great if you want to keep audit logs of responses from remote servers.
You could use the class name, and do some normalization. You could also
parse the message that Gitlab provides, but that has some other issues:
1. You need to know all the possible error classes Gitlab implements to
handle error responses.
2. Parsing string is not the best way to do this.
3. It becomes a bigger issue if you integrate with different
Git Hostings that use different libraries and handle errors in different
ways.
Status codes are the canonical way to know what happened with
an http request. They are agnostic to programming languages,
libraries, producers, and …
> Expose response status when Gitlab raises an error.

- lib/gitlab/client.rb
- lib/gitlab/client/runners.rb
- spec/fixtures/project_runner_enable.json
- spec/fixtures/project_runners.json
- spec/fixtures/runner.json
- spec/fixtures/runner_delete.json
- spec/fixtures/runner_edit.json
- spec/fixtures/runners.json
- spec/fixtures/runners_all.json
- spec/gitlab/client/runners_spec.rb
This pull request (as titled) adds in runner support:
* List users runners
* List all runners (if admin)
* List projects runners (specific)
* Get runner
* Update runner
* Delete runner
* Enable project runner
* Disable project runner
> Add in GitlabCI Runner support

- .travis.yml
- CHANGELOG.md
- gitlab.gemspec
1.9.x and 2.0.x are both EOL, they're no longer supported with security releases. Travis builds were failing due to terminal-table releasing a breaking change for old Ruby versions in a patch version.
> Lock terminal-table version to provide support for Ruby 1.9 and 2.0.

- CHANGELOG.md
- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
Adds method + test (rspec) in Projects to share a project with a group.
Resolves #214
> Add method `share_project_with_group`

- CHANGELOG.md
- README.md
- lib/gitlab/client/branches.rb
- lib/gitlab/client/build_triggers.rb
- lib/gitlab/client/build_variables.rb
- lib/gitlab/client/builds.rb
- lib/gitlab/client/commits.rb
- lib/gitlab/client/groups.rb
- lib/gitlab/client/issues.rb
- lib/gitlab/client/labels.rb
- lib/gitlab/client/merge_requests.rb
- lib/gitlab/client/milestones.rb
- lib/gitlab/client/namespaces.rb
- lib/gitlab/client/notes.rb
- lib/gitlab/client/projects.rb
- lib/gitlab/client/repositories.rb
- lib/gitlab/client/repository_files.rb
- lib/gitlab/client/runners.rb
- lib/gitlab/client/services.rb
- lib/gitlab/client/snippets.rb
- lib/gitlab/client/system_hooks.rb
- lib/gitlab/client/tags.rb
- lib/gitlab/client/users.rb
Update relevant documentation links for the client classes to point to https://docs.gitlab.com instead of the GitHub mirror of the repository.
> Update documentation links to use docs.gitlab.com.

- .travis.yml
- CHANGELOG.md
- README.md
- gitlab.gemspec
This is the result from the discussion in https://github.com/NARKOZ/gitlab/issues/217 👍
> Remove the Ruby 1.x support in the gemspec

- lib/gitlab/client/users.rb
- spec/gitlab/client/users_spec.rb
This pull request implements the API call for https://docs.gitlab.com/ce/api/users.html#list-ssh-keys-for-user.
> Allow to retrieve ssh_keys for a specific user

- lib/gitlab/client.rb
- spec/gitlab/client/client_spec.rb
This PR masks the token when invoking `inspect` on gitlab client.
So when people do bug report, they won't accidentally pasted token information. [other client library](https://github.com/octokit/octokit.rb/blob/c1e66093eeb499c59e49212ca10c2a4efc356836/lib/octokit/client.rb#L118-L133) also does this.
> Mask the token when inspect the client object

- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
While I was looking how to best transfer git repos from bitbucket to gitlab, I found this gem very useful.
I have to transfer a lot of repos, on the first repo, I have to create deploy keys, but then later on, I only needed to enable those already created deploy keys on the other repos.
I added two functions: enable_deploy_key and disable_deploy_key to the client/repositories.rb
file, to accompany the other deploy keys functions.
These parts of the API are described here:
https://docs.gitlab.com/ee/api/deploy_keys.html#enable-a-deploy-key
Further added spec tests for these new functions.
> Add methods to disable and enable deploy keys on projects.

- lib/gitlab/client/repositories.rb
- lib/gitlab/file_response.rb
- spec/gitlab/file_response_spec.rb
This allows downloading a repository archive. Uses the same structure as for downloading build artifacts.
See http://docs.gitlab.com/ce/api/repositories.html#get-file-archive for more details.
> Add repo_archive method

- lib/gitlab/client.rb
- lib/gitlab/client/pipelines.rb
- spec/fixtures/pipeline.json
- spec/fixtures/pipeline_cancel.json
- spec/fixtures/pipeline_create.json
- spec/fixtures/pipeline_retry.json
- spec/fixtures/pipelines.json
- spec/gitlab/client/pipelines_spec.rb
Implements the pipeline API from https://docs.gitlab.com/ce/api/pipelines.html
- list pipelines
- get a single pipeline
- create a new pipeline
- retry failed builds in a pipeline
- cancel a pipelines builds
closes #248
> Support pipeline

- CHANGELOG.md
- lib/gitlab/client/issues.rb
- spec/gitlab/client/issues_spec.rb
You can use `int` based ID to identify a project, or you can use `NAMESPACE/REPO` according to the API documentation: https://docs.gitlab.com/ce/api/projects.html#get-single-project
The advantage of using `NAMESPACE/REPO` everywhere, is that you don't need to first load the repository to get the numeric ID so you can use it on other places.
The gem itself already allows the use of the "literal" identification, but there is one check in the issues getter that prevents it's use. This PR fixes that.
cc @NARKOZ @connorshea @asedge
> Allow issues to use NAMESPACE/REPO identifier

- CHANGELOG.md
- lib/gitlab/client/issues.rb
- lib/gitlab/client/merge_requests.rb
- spec/gitlab/client/issues_spec.rb
- spec/gitlab/client/merge_requests_spec.rb
This resolves #221
Note that the documentation in the issue is incorrect wrt to the
unsubscribe endpoints.  Latest Gitlab documentation indicates that a
`POST` to `.../unsubscribe` is the correct method, rather than `DELETE`.
Also, verbs are `subscribe`/`unsubscribe` rather than `subscription`
> (Un)subscribe to issues and merge_requests

- CHANGELOG.md
- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
This PR resolves issue #222. The `deploy_keys` endpoints have been updated from `keys`. `disable_deploy_key` was already updated.
This has been tested against <https://gitlab.com/api/v3> and is confirmed working. This does not address backwards compatibility with versions prior to 8.10.
> Fixes #222, using deploy_keys endpoint

- CHANGELOG.md
- lib/gitlab/client/commits.rb
- spec/fixtures/project_commit_create.json
- spec/gitlab/client/commits_spec.rb
* the user can now create commits through the gem by posting
one or more file changes (file content).  This can be extremely
useful in situations where you don't want to distribute ssh keys,
and use api tokens instead with CI systems.
> Adds ability to create commits

- gitlab.gemspec
The latest version of `terminal-table` is compatible with ruby 2.0 again, see https://github.com/tj/terminal-table/pull/80
> Remove version-lock for terminal-table

- lib/gitlab/client.rb
- lib/gitlab/client/keys.rb
- spec/gitlab/client/keys_spec.rb
This pull request adds support for the keys resource: https://docs.gitlab.com/ce/api/keys.html.
> client: add support for the keys resource

- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
This makes it easier to tests using a rack-based Gitlab mock API. (Sinatra in my case)
Rack will assume POST requests include `www-form-urlencoded` data, but it won't assume the same of PUT or PATCH requests, and therefore won't parse the body unless a header is present.  Granted, this header is obviously not required for Gitlab to accept the request, but it's the right way to construct the request in general, which should make it more reusable/compatible with testing frameworks, etc.
It seems like `HTTParty` or even `Net::HTTP` is making the decision to encode the data as form-encoded data, so why it doesn't automatically attach that header, I'm not sure.  But that's further than I have time to investigate/fix at the moment :)
Note: I have not yet tested this patch with an actual Gitlab …
> Add appropriate Content-Type header

- lib/gitlab/client/branches.rb
In Gitlab 9.0 the `branch_name` parameter for the `create_branch` method was renamed to `branch` (see: https://gitlab.com/gitlab-org/gitlab-ce/issues/22132)
This pull request renames the parameter for the client.
> Rename branch_name parameter to branch in create_branch method

- lib/gitlab/client/commits.rb
- spec/gitlab/client/commits_spec.rb
The `branch_name` parameter for the `create_commit` was renamed to `branch` in Gitlab 9.0.
This pull request changes the parameter in the client.
> Rename branch_name parameter to branch in create_commit method

- lib/gitlab/client/merge_requests.rb
- lib/gitlab/client/notes.rb
- spec/gitlab/client/notes_spec.rb
1. Modify and delete wall notes, issue notes, snippet notes and MR notes methods added to notes.rb
2. Cleaning up duplicate MR comment methods in merge_requests.rb
3. Adding aliases for existing MR comment/note methods to notes.rb
> edit and delete methods for notes API

- lib/gitlab/client/commits.rb
- spec/gitlab/client/commits_spec.rb
Currently when creating a commit the POST data is send via the query parameter. This leads to the Gitlab API to respond with 414 URI too long once there are several documents part of the commit.
This can be fixed when sending the data via the POST body attribute.
> Use body parameter to send post data

- lib/gitlab/client/repository_files.rb
- spec/gitlab/client/repository_files_spec.rb
New path for all endpoints is `repository/files/:file_path` (instead of passing file_path as a parameter)
> Update repository files endpoint for APIv4

- lib/gitlab/client/labels.rb
- spec/fixtures/label.json
- spec/fixtures/label_unsubscribe.json
- spec/gitlab/client/labels_spec.rb
Two missing methods for the labels API:
* `subscribe_to_label`: Subscribes the user to a label for notifications
* `unsubscribe_from_label`: Unsubscribes the user from a label
> Subscribe and unsubscribe actions for labels

- lib/gitlab/client/labels.rb
Labels can have a description and a priority in addition to name and color.
It's now possible to provide them when creating or editing a label.
> Add options to Labels#create_label

- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
Fixes a few copy and paste errors, along with clarifying that any valid option can be passed in.
> Fix and clarify edit_project's option docs

- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
Current method `project_search` doesn't work.
Indeed, the APIv4 is now using query parameter to this.
I made the modifications according to this new behavior.
> Replace `projects/search/{query}` by `projects?search={query}`

- lib/gitlab/client/commits.rb
For some reason two methods in `Commits` didn't use `url_encode` for id / name, which caused an error in my project. My suggestion is to keep it consistent.
> Use url_encode in all commit resources

- lib/gitlab/client/issues.rb
- spec/gitlab/client/issues_spec.rb
This PR adds support for moving an issue based on http://docs.gitlab.com/ce/api/issues.html#move-an-issue.
It has been used at @trainline-eu.
Closes #227
> Add support for moving an issue

- lib/gitlab/client/issues.rb
- spec/gitlab/client/issues_spec.rb
Hello,
This PR adds the Time Tracking features (set/reset time estimate, set/reset time spent, display time stats) for an Issue.
Cf https://docs.gitlab.com/ee/api/issues.html#set-a-time-estimate-for-an-issue
I hope this helps! This is my 1st contribution here, let me know if something is missing!
> Add time tracking for issues

- lib/gitlab/error.rb
- spec/gitlab/error_spec.rb
I came across an issue using this gem where I needed the response returned by the error'd HTTP request. Rather than dig into the ivars or private methods, this exposes the `parsed_response#message` itself. The PR also includes a lump of cleanup work on the spec.
> Add #response_message accessor to GitLab::Error::ResponseError

- lib/gitlab/client/build_variables.rb
- spec/gitlab/client/build_variables_spec.rb
- spec/gitlab/shell_spec.rb
Added support for group level variables as described here: https://docs.gitlab.com/ce/api/group_level_variables.html
Fixed a couple copy/paste errors in the documentation of variables and update_variable.
> Add support for group level variables

- lib/gitlab/client/branches.rb
Getting 404 error from gitlab when requesting branch from API:
```ruby
Gitlab.branch(project_id, branch_name)
```
It happen when `branch` variable contains slash in it.
I found that latest gitlab releases require to encode branch name in its request url.
Example:
1. 404 Not Found
https://gitlab.com/api/v4/projects/14022/repository/branches/feature/gitaly-feature-flag
2. 200 OK (when logged in)
https://gitlab.com/api/v4/projects/14022/repository/branches/feature%2Fgitaly-feature-flag
[Here is](https://gitlab.com/gitlab-org/gitlab-ce/issues/24471) related issue on gitlab project.
And one more [related issue](https://github.com/NARKOZ/gitlab/issues/289) on this project.
But even if it may be considered as a bug in gitlab, I think it's better to encode branch names when doing such api …
> Error 404 not found when requesting branch, containing slash ('/'), from API

- lib/gitlab/api.rb
- spec/gitlab/api_spec.rb
This patch adds `User-Agent` header
Closes #338 
/cc: @axilleas
> Add User-Agent header to Gitalb::API

- lib/gitlab/client/groups.rb
- lib/gitlab/version.rb
- spec/fixtures/group_edit.json
- spec/fixtures/group_subgroups.json
- spec/gitlab/client/groups_spec.rb
- spec/gitlab/shell_spec.rb
Hi there,
First of all thanks for the hard work, this week I've tried use the gem and i've found that are missing some api methods at groups.rb, so i take some time to add the following methods:
- List Groups Subgroups based on the group ID we send on the API call (https://docs.gitlab.com/ce/api/groups.html#list-a-groups-s-subgroups)
- Edit group method, based on the group ID we send on the API call (https://docs.gitlab.com/ce/api/groups.html#update-group)
Besides this, i've added the fixtures and specs for testing this new 2 methods.
> Added subgroups and group_edit methods

- lib/gitlab/client/tags.rb
- spec/gitlab/client/tags_spec.rb
When a git tag contain characters with a special meaning in a url, then this library would send requests to the wrong urls. Examples of such characters are '/' and '#'.
This PR makes sure that such characters are properly url-encoded.
> Fixes error when tags contain special characters

- lib/gitlab/client/branches.rb
- spec/gitlab/client/branches_spec.rb
```ruby
g = Gitlab.client(endpoint: 'https://gitlab.com/api/v4', private_token: 'xxxx')
g.create_branch(5221359, "newbranch", "master")
=> #<Gitlab::ObjectifiedHash:70145150190240 {hash: {"name"=>"newbranch", ~ 
```
- https://docs.gitlab.com/ce/api/branches.html#create-repository-branch
Thanks in advance :bow:
> Fix create branch API

- lib/gitlab/client/tags.rb
https://docs.gitlab.com/ee/api/tags.html#create-a-new-tag
parameter name is `release_description`
> Rename create_tag param

- lib/gitlab/client.rb
- lib/gitlab/client/access_requests.rb
- spec/fixtures/access_request.json
- spec/fixtures/access_requests.json
- spec/fixtures/approved_access_request.json
- spec/fixtures/default_approved_access_request.json
- spec/gitlab/client/access_requests_spec.rb
- spec/gitlab/shell_spec.rb
Group/Project Access Requests API
Methods to
- List access requests to a group/project
- Make access request to a group/project
- Approve access request to a group/project
- Deny access request to a group/project
Closes #315
> [FEATURE] Group/Project Access Requests API

- lib/gitlab/client/labels.rb
Add `options` parameter to labels method to allow `per_page` parameter
> allow options parameter in labels

- lib/gitlab/client/groups.rb
The group ID can be a String, similar to a project ID, and so needs
to be encoded.
> URL encode Group ID

- gitlab.gemspec
Background: I want to use gitlab gem to run in a CLI and vendor all the dependencies. Gitlab was the largest with over 1MB. Granted, compared to node_modules the overhead is tiny, but nevertheless there are some needless configs that are shipped with the Gem but never needed for a usage.
Removed /specs + Docker configs + Dev configs
Size of the unzipped gem dir:
Before: 1,4MB 
After: 380KB (-72%)
Instead of reject { .. regex } one could use grep_v, which is available from Ruby 2.3. I was not sure, if you are supporting Ruby 2.2 and lower though.
> Removed unnecessary files from Gemspec to reduce file size of distributed gem

- lib/gitlab.rb
- lib/gitlab/client/projects.rb
- lib/gitlab/configuration.rb
- lib/gitlab/page_links.rb
- lib/gitlab/paginated_response.rb
- lib/gitlab/request.rb
- spec/fixtures/team_member.json
- spec/gitlab/client/projects_spec.rb
1. Added `expires_at` as an option to adding and editing team members to a project
2. Updated `fixtures/team_member.json` to current schema
Closes #408
> [UPDATE] Added expires_at option to team members in a project

- lib/gitlab/client.rb
- lib/gitlab/client/versions.rb
- spec/fixtures/version.json
- spec/gitlab/client/versions_spec.rb
This PR adds support for the Version api that was added in GitLab 8.13.
https://docs.gitlab.com/ce/api/version.html
> Add support for Version API

- lib/gitlab/client/commits.rb
- spec/gitlab/client/commits_spec.rb
Added method to cherry pick a commit
`Gitlab.cherry_pick_commit(project_id, sha, branch)`
closes #423
> Added Cherry pick a commit client method

- lib/gitlab/client/issues.rb
- spec/fixtures/participants_on_issue.json
- spec/gitlab/client/issues_spec.rb
Adds missing 'Participants on issues' endpoint and spec.
Documentation reference: https://docs.gitlab.com/ce/api/issues.html#participants-on-issues
> Add 'Participants on issues' endpoint

- lib/gitlab/client/pipelines.rb
- spec/gitlab/client/pipelines_spec.rb
@NARKOZ as mentioned in #401, here is a new MR with the updated code. :)
Unfortunately the Gitlab API does not allow an empty `variables` parameter, so it is necessary to add this `if variables.any?` check... Maybe you know a better way how to ensure that the `variables` parameter is only set when at least one variable is passed?
> Allow passing variables when creating a pipeline

- lib/gitlab/error.rb
- spec/gitlab/error_spec.rb
This fixes `error.rb` so that it handles error responses created by Gitlab.com's spam protection
correctly. The error message is nested in a slightly off way (I believe
this is a bug), causing the error message formatting code to blow up as
it tries to join a string.
I admit doing `[val].flatten` feels a bit hackish, but the alternative (nested ternaries) is also not pretty. :)
> Fixes a bug in handling "Spam detected" messages

- lib/gitlab/client/milestones.rb
- spec/gitlab/client/milestones_spec.rb
`Gitlab.delete_milestone(project, milestone_id)`
Closes #431
> Deleting a project milestone

- lib/gitlab/client/branches.rb
- spec/gitlab/client/branches_spec.rb
`Gitlab.delete_merged_branches(project)`
Closes #433
> Deleting all merged branches in a project

- lib/gitlab/client/branches.rb
- spec/fixtures/protected_branch.json
- spec/fixtures/protected_branches.json
- spec/gitlab/client/branches_spec.rb
`Gitlab.protected_branches(project)`
`Gitlab.protected_branch(project, branch)`
Closes #434
> Protected branches missing methods

- lib/gitlab/client.rb
- lib/gitlab/client/broadcast_messages.rb
- spec/fixtures/broadcast_message.json
- spec/fixtures/broadcast_messages.json
- spec/gitlab/client/broadcast_messages_spec.rb
**Broadcast messages API**
`Gitlab.broadcast_messages`
`Gitlab.broadcast_message(id)`
`Gitlab.create_broadcast_message(message, options = {})`
`Gitlab.edit_broadcast_message(id, options = {})`
`Gitlab.delete_broadcast_message(id)`
Closes #436
> Added BroadcastMessages API

- lib/gitlab/client/pipelines.rb
Reverts NARKOZ/gitlab#445
@NARKOZ 
I am sorry for the PR, HTTParty will encode query if we pass it in query parameter.
I was using 1.5.0 version, the error would occurs because we pass query in url.
can you help me revert the PR?
thanks
> Revert "fix uri error when ref includes chinese like hotfix/崩溃"

- lib/gitlab/client.rb
- lib/gitlab/client/project_badges.rb
- spec/fixtures/preview_project_badge.json
- spec/fixtures/project_badge.json
- spec/fixtures/project_badges.json
- spec/gitlab/client/project_badges_spec.rb
**Project Badges API**:
```rb
Gitlab.project_badges(project)
Gitlab.project_badge(project, badge_id)
Gitlab.add_project_badge(project, options = {})
Gitlab.edit_project_badge(project, badge_id, options = {})
Gitlab.remove_project_badge(project, badge_id)
Gitlab.preview_project_badge(project, link_url, image_url)
```
closes #402
> Project Badges API

- lib/gitlab/client/merge_request_approvals.rb
- spec/gitlab/client/merge_request_approvals_spec.rb
Updates URL to match [docs](https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-allowed-approvers-for-merge-request).
> Use correct URL for edit_merge_request_approvers

- lib/gitlab/client/pipelines.rb
- spec/gitlab/client/pipelines_spec.rb
```rb
Gitlab.delete_pipeline(project, pipeline_id)
```
Closes #455
> Added delete_pipeline API

- lib/gitlab/client.rb
- lib/gitlab/client/resource_label_events.rb
- spec/fixtures/resource_label_event.json
- spec/fixtures/resource_label_events.json
- spec/gitlab/client/resource_label_events_spec.rb
I noticed that the resource label events api was not implemented and I have to use this in a script of ours.  I have completed the full API here and added tests which seem to conform to your style (please let me know if it is missing anything).
> adds the resource label events api to the gitlab client

- .rubocop.yml
- lib/gitlab/error.rb
- lib/gitlab/request.rb
- spec/gitlab/error_spec.rb
Gitlab may respond with a 429 error and a message of 'Retry later'.  The
response body in this case has content-type 'text/plain'. This change
adds support for 429 errors and processes the body of responses with
content formated as 'text/plain'.
Should fix issue #458.
> Add support to handle 429 responses from a rate limited gitlab instance

- lib/gitlab/client.rb
- lib/gitlab/client/group_labels.rb
- lib/gitlab/client/labels.rb
- spec/fixtures/group_label.json
- spec/fixtures/group_label_unsubscribe.json
- spec/fixtures/group_labels.json
- spec/gitlab/client/group_labels_spec.rb
- spec/gitlab/shell_spec.rb
Group Label API support is being added in GitLab 11.8 (February 22nd)
and is available now on gitlab.com!
> Add Group Label support

- lib/gitlab/client/boards.rb
- spec/fixtures/board.json
- spec/fixtures/updated_board.json
- spec/gitlab/client/boards_spec.rb
Missing project issue board endpoints:
```ruby
Gitlab.board(project, id)
Gitlab.create_board(project, name)
Gitlab.edit_board(project, id, options = {})
Gitlab.delete_board(project, id)
```
Closes #468
> Adding missing endpoints in project issue boards

- lib/gitlab/client.rb
- lib/gitlab/client/search.rb
- spec/fixtures/search_blobs_results.json
- spec/fixtures/search_commits_results.json
- spec/fixtures/search_issues_results.json
- spec/fixtures/search_merge_requests_results.json
- spec/fixtures/search_milestones_results.json
- spec/fixtures/search_notes_results.json
- spec/fixtures/search_projects_results.json
- spec/fixtures/search_snippet_blobs_results.json
- spec/fixtures/search_snippet_titles_results.json
- spec/fixtures/search_wiki_blobs_results.json
- spec/gitlab/client/search_spec.rb
Search API
```ruby
Gitlab.search_globally(scope, search)
Gitlab.search_in_group(group, scope, search)
Gitlab.search_in_project(project, scope, search)
```
Closes #469
> Adding APIs for global search, search in projects and in groups

- lib/gitlab/client.rb
- lib/gitlab/client/container_registry.rb
- spec/fixtures/registry_repositories.json
- spec/fixtures/registry_repository_tag.json
- spec/fixtures/registry_repository_tags.json
- spec/gitlab/client/container_registry_spec.rb
Container Registry API
```ruby
Gitlab.registry_repositories(project)
Gitlab.delete_registry_repository(project, id)
Gitlab.registry_repository_tags(project, repository_id) 
Gitlab.registry_repository_tag(project, repository_id, tag_name) 
Gitlab.delete_registry_repository_tag(project, repository_id, tag_name)
Gitlab.bulk_delete_registry_repository_tags(project, repository_id, options = {})
```
Closes #471
> Container Registry API

- lib/gitlab/client.rb
- lib/gitlab/client/markdown.rb
- spec/fixtures/markdown.json
- spec/gitlab/client/markdown_spec.rb
Markdown API
```ruby
Gitlab.markdown(options = {})
```
Closes #472
> Markdown API

- lib/gitlab/client.rb
- lib/gitlab/client/lint.rb
- spec/fixtures/invalid_content_gitlab_ci_yml.json
- spec/fixtures/no_content_gitlab_ci_yml.json
- spec/fixtures/valid_content_gitlab_ci_yml.json
- spec/gitlab/client/lint_spec.rb
```ruby
Gitlab.validate_gitlab_ci_yml(content)
```
Closes #473
> Validate .gitlab-ci.yml API

- lib/gitlab/client/merge_request_approvals.rb
- spec/gitlab/client/merge_request_approvals_spec.rb
Updating the approvers API endpoint to align with the gitlab docs:
Reference: https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-allowed-approvers
> Correct API endpoint for project approvers

- lib/gitlab/client/runners.rb
- spec/gitlab/client/runners_spec.rb
Ran into an issue where I needed to pass options to `runner_jobs`, so I've added the ability to do so.  Similar to #475 in spirit but passes through the full `options` hash rather than just a `status` argument.  Also updated the tests to include passing in the option.
> Add options to runner_jobs

- lib/gitlab/client/merge_request_approvals.rb
- spec/gitlab/client/merge_request_approvals_spec.rb
Fix edit_project_approvers to use correct API path & update comments to properly reflect options as required, and to set to nil if you want one or both of them empty.
> Edit approvals/approvers fix

- README.md
Accessing https://rubydoc.info/ gives an SSL error since their certificate only covers `www.rubydoc.info`.
> Added www in front of rubydoc.info

- lib/gitlab/client/repositories.rb
This PR adds support for choosing which archive format when downloading the archive for a repository. 
This follows the docs here: https://docs.gitlab.com/ee/api/repositories.html#get-file-archive
> Add format option to repo_archive

- lib/gitlab/error.rb
I've ran into this when [accepting a MR](https://docs.gitlab.com/ce/api/merge_requests.html#accept-mr), which can return a 406 status code.
> Raise exception on HTTP status 406

- lib/gitlab/client/commits.rb
- spec/fixtures/project_commit_refs.json
- spec/gitlab/client/commits_spec.rb
See https://docs.gitlab.com/ee/api/commits.html#get-references-a-commit-is-pushed-to
> Add support for commit refs API

- lib/gitlab/client/repositories.rb
Hi there 👋 
While using the `tree`  method of Repositories I noticed one small discrepancy with the actual API.
Although it's not documented in code, there's one other option of passing the `per_page` value to configure how many results you want per page.
See https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree
I've used this with the actual version of this wrapper and it's working 👍 
It's just a matter of updating the documentation.
Thanks for this wrapper! It's super useful 😄
> Updating Repositories code documentation

- README.md
- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
The `Gitlab::Client` initializer allows you to pass an `httparty` option
to provide additional options to the internal HTTParty client. This is great!
However, previously the `Gitlab::Request` class would overwrite the
`headers` value in order to set its authorization token.
Now, we merge the authorization token with any user-defined HTTParty
header arguments.
> Allow custom header arguments via `httparty` option

- README.md
- lib/gitlab/configuration.rb
Gitlab CI Provides CI_API_V4_URLfor the V4 API as of 11.7. It'd be nice to just pick that up if using the gem in a gitlab ci job.
> Add the gitlab CI variable as a fallback for Gitlab.endpoint

- lib/gitlab/client/projects.rb
- lib/gitlab/client/search.rb
- spec/gitlab/client/projects_spec.rb
The `upload_file` api expects the file argument to be passed using a `File.open()` ie. a file object explicitly, to allow multipart upload. While this may work for someone working inside irb or a ruby app, but for Gitlab CLI, it becomes tougher to use for the common folk.
**Suggestion (and changes made):**
Take the fullpath of the file to be uploaded as argument, and then use the `File.open` logic inside the method to upload the file as multipart. This will make it consistently usable for both irb and CLI.
Closes #510
> [FIX] Moving file open logic to upload_file from args to support CLI

- lib/gitlab/client/repository_files.rb
- spec/fixtures/get_file_blame.json
- spec/gitlab/client/repository_files_spec.rb
Detailed at  [get file blame from repository](https://docs.gitlab.com/ee/api/repository_files.html#get-file-blame-from-repository)
> add support for file blame API

- lib/gitlab/client/commits.rb
- lib/gitlab/client/repositories.rb
- spec/gitlab/client/commits_spec.rb
Gitlab API v4 uses the get parameter `ref` instead of `ref_name` when listing commits and files. Current documentation does not reflect that change. Its confusing because when `ref_name` is used, API will just default to master. We tested it in our server (master contains 9 files and version 1.0.0 has 7):
```
irb(main):061:0> g.tree(5419,ref_name: '1.0.0').count
=> 9
irb(main):062:0> g.tree(5419,ref: '1.0.0').count
=> 7
```
> Options hash documentation for tree and commits methods is outdated

- lib/gitlab/error.rb
- spec/gitlab/error_spec.rb
An error response may contain useful additional context, and this allows
users to access that context on the exception class.
For example, the cherry-pick API now includes an `error_code` field to
indicate why the cherry-pick failed, which can now be accessed via
`Error#error_code`.
> Forward missing messages on Error to the parsed response

- lib/gitlab/client/groups.rb
- spec/gitlab/client/groups_spec.rb
The Group details API has support for two optional flags, which include
custom attributes in the response, and allows limiting the details
returned.
See https://docs.gitlab.com/ee/api/groups.html#details-of-a-group
> Support optional parameters to `.group`

- lib/gitlab/client/merge_request_approvals.rb
Fixes #531 
This enables the use of `sudo` for this method and allows for automation
where the approval of a certain user need to be removed.
> Add options hash to unapprove_merge_request

- lib/gitlab/client.rb
- lib/gitlab/client/epics.rb
- spec/fixtures/epic.json
- spec/fixtures/epics.json
- spec/gitlab/client/epics_spec.rb
GitLab has Epics for paid subscriptions, or licenced products. To
interact with them, basic CRUD action support is added by this change.
> Add support for Epic CRUD actions

- lib/gitlab/error.rb
- spec/gitlab/error_spec.rb
This reverts commit 216251a554e2392ed22e61ef279bd7d4008fa1f0, reversing
changes made to e10c7e2a840666518d679f426082b1fbc6753aea.
After updating to 4.13.0 in https://gitlab.com/gitlab-com/chatops, I started seeing unexpected spec failures related to argument counts and `method_missing` on `ObjectifiedHash`, so for the time being I think it's best to revert this feature until it can be properly re-implemented.
I suggest a 4.13.1 patch release after this revert.
> Revert "Merge pull request #530 from rspeicher/rs-error-method-missing"

- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
Consider the following script:
```ruby
require 'gitlab'
client = Gitlab::Client.new(
endpoint: 'https://gitlab.com/api/v4',
private_token: '[REDACTED]'
)
args = { per_page: 10 }
puts args.inspect
client.get('/projects', args)
puts args.inspect
```
Prior to this change, this would output:
{:per_page=>10}
{:per_page=>10, :headers=>{"PRIVATE-TOKEN"=>"[REDACTED]"}}
Which would be a problem if a user were logging the parameters they were
passing to a `PUT` endpoint inside a loop, for example. The first log
message would have their parameters, while subsequent logs would have
their parameters plus their private token.
This is unexpected behavior that could expose credentials.
Now we duplicate the user parameters before modifying them in-place.
> Avoid modifying request parameters in-place

- lib/gitlab/client/jobs.rb
- spec/gitlab/client/jobs_spec.rb
This adds a method for deleting job artifacts.
If you never set expiration for your artifacts and now need a mass delete, this function will help.
> Add a method to delete job artifacts

- lib/gitlab/client/repositories.rb
- spec/fixtures/contributors.json
- spec/gitlab/client/repositories_spec.rb
Added a function `Gitlab.contributors(...)` to enable access to the GitLab repository contributors API.
https://docs.gitlab.com/ee/api/repositories.html#contributors
> Add repository contributors API

- lib/gitlab/client/users.rb
- spec/fixtures/activities.json
- spec/gitlab/client/users_spec.rb
Adds `Gitlab.activities`, valid for admin auth tokens only: https://docs.gitlab.com/ee/api/users.html#get-user-activities-admin-only
> Implement GET /user/activities

- lib/gitlab/paginated_response.rb
- spec/gitlab/paginated_response_spec.rb
Fixes #494
There can be a mismatch in the API endpoint and the pagination endpoint. In our use-case, we whitelist the Gitlab API on `gitlab-internal.domain.com`, whereas the web interface `gitlab.domain.com` cannot contact the API. However, Gitlab pagination links point to `gitlab.domain.com` which does not work. There seem to be some other use cases in #494 and #521.
This change is to trust that the gem is configured with the appropriate endpoint. The assumption is that only the domain prefix would be different and not the api version-that could cause additional issues and should fail.
> Thoroughly remove the client prefix for pagination response

- lib/gitlab/error.rb
- spec/gitlab/error_spec.rb
Sometimes the Gitlab API responds with an error code with incorrect
content-type headers. (application/json header with text/plain body)
This causes a Parsing error to be raised instead
of the api error (e.g. throttling). This change updates
ResponseError to ignore parsing errors so that the original api error
is still raised.
The specific scenario I've noticed was a 429 response from the Gitlab API. The body was an html error page:
```
message: "765: unexpected token at '<!DOCTYPE html>
<html>
<head>
<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
<title>429 Too Many Requests</title>
<style>
body {
color: #666;
text-align: center;
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
margin: auto;
font-size: 14px;
}
h1 {
font-size: 56px; …
```
> Prevent error obfuscation on json parse errors

- bin/console
- lib/gitlab/client/merge_request_approvals.rb
- spec/fixtures/merge_request_approval_state.json
- spec/gitlab/client/merge_request_approvals_spec.rb
This merge implements the API function merge_request_approval_state introduced in Gitlab 12.6.
https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-the-approval-state-of-merge-requests
And implements issue #564
> implementation of merge_request_approval_state

- lib/gitlab/paginated_response.rb
- spec/gitlab/paginated_response_spec.rb
This preserves compatibility with the existing pagination methods while leveraging a lazy enumerator to simplify the implementation.  The other advantage is that using the new `lazy_paginate` method directly allows users to take advantage of all the additional methods available to lazy enumerators, such as `take` or `first`, without needing to code those methods into this library.
> Simplify pagination using Enumerator::Lazy

- lib/gitlab/objectified_hash.rb
- spec/gitlab/objectified_hash_spec.rb
At the moment ObjectifiedHash is missing out on hierarchies of objects where there are hashes contained within an array. Which is annoying as it happens in a lot of API calls.
This just adds an extra step to the initialiser of ObjectifiedHash so that arrays of hashes are handled properly
> Add support for nested arrays on ObjectifiedHash (take 2)

- lib/gitlab/client/merge_requests.rb
For #572, the options to remove branch while creating/accepting MR are already available (the options hash can take any valid value permissible by the gitlab API), they are not included in the documentation accompanying those methods. Updated relevant sections.
> Updated options documentation for create MR and accept MR

- lib/gitlab/client/users.rb
Adds the `skip_confirmation` parameter to the `Users#add_email` method for the user API.
> add skip_confirmation param to add email

- lib/gitlab/error.rb
- spec/fixtures/cherry_pick_commit_failure.json
- spec/gitlab/client/commits_spec.rb
- spec/gitlab/error_spec.rb
An error response may contain useful additional context, and this allows
users to access that context on the exception class.
For example, the cherry-pick API now includes an error_code field to
indicate why the cherry-pick failed, which can now be accessed via
`ResponseError#error_code`.
This is a second attempt at https://github.com/NARKOZ/gitlab/pull/530, without abusing `method_missing`.
> Support error_code returned by specific API endpoints

- lib/gitlab/client/commits.rb
- spec/fixtures/revert_commit_failure.json
- spec/gitlab/client/commits_spec.rb
The [commit revert API](https://docs.gitlab.com/ee/api/commits.html#revert-a-commit) was added in GitLab 11.5, and I was surprised to see it's not yet added to the gem, so I've added it here.
Additionally, as of 13.3 the cherry-pick and revert APIs will support a `dry_run` flag, which prevents committing any potential changes. This PR adds support for that in both APIs as well.
> Support cherry-pick dry runs, and add revert support

- lib/gitlab/client.rb
- lib/gitlab/client/resource_state_events.rb
- spec/fixtures/issue_resource_state_event.json
- spec/fixtures/issue_resource_state_events.json
- spec/fixtures/mr_resource_state_event.json
- spec/fixtures/mr_resource_state_events.json
- spec/gitlab/client/resource_state_events_spec.rb
- spec/gitlab/shell_spec.rb
Resource state events represent the states that the MR or Issue has transitioned in its life time.
This allows us to track, which state was set, who did it, and when it happened.
1. Resource state events api's added
2. Linking resoruce state event module into client.rb
Resource state event api added in Gitlab 3.2
More information [here](https://docs.gitlab.com/13.2/ee/api/resource_state_events.html#list-project-merge-request-state-events)
> Feature : Resource State Events API Addition

- lib/gitlab/client/runners.rb
- lib/gitlab/help.rb
- spec/fixtures/group_runners.json
- spec/gitlab/cli_spec.rb
- spec/gitlab/client/runners_spec.rb
- spec/gitlab/objectified_hash_spec.rb
Closes #581 
Also 
1. removed a few deprecated options
2. fixed the update method to use `body` instead of `query`
3. updated tests
> Updating the runners API

- lib/gitlab/client/groups.rb
- spec/fixtures/group_billable_members.json
- spec/gitlab/client/groups_spec.rb
Added the method according to the documentation from Gitlab https://docs.gitlab.com/ee/api/members.html\#list-all-billable-members-of-a-group
> Adding the group billable members call as described in the Gitlab documentation

- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
The purpose of this MR is to implement a method to list all members including inherited members. Currently in the rudy sdk we have available only two methods, that don't return the inherited ones.
- `team_members`, `group_members` - Gets a list of group or project members viewable by the authenticated user. Returns only direct members and not inherited members through ancestors groups.
Rather than trying to find a workaround(although I am not sure there is one) I think it is a good idea to have this endpoint as in the REST API that will return all members.
> Add method to list all members including inherited members

- .rubocop.yml
There's only one method with 4 optional parameters: 
```
$git blame lib/gitlab.rb | grep def\ self.http_proxy
33654bf1 (Nihad Abbasov    2018-08-07 13:34:00 +0400 37)   def self.http_proxy(address = nil, port = nil, username = nil, password = nil)
```
> allow max 4 optional parameters for passing self.http_proxy()

- lib/gitlab/client/merge_requests.rb
- spec/fixtures/merge_request_rebase.json
- spec/gitlab/client/merge_requests_spec.rb
* Adds method to rebase merge request
> add rebase merge request method

- lib/gitlab.rb
- lib/gitlab/cli.rb
- lib/gitlab/help.rb
- spec/gitlab/client/build_variables_spec.rb
- spec/gitlab/client/users_spec.rb
I ran into a problem (wrong number of arguments) passing optional params to the variables endpoint using Ruby 3.
The problem related to this change: Keyword arguments are separated from other arguments (https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/).
> Ruby 3 support

- lib/gitlab/client/merge_request_approvals.rb
- spec/fixtures/merge_request_level_rule.json
- spec/gitlab/client/merge_request_approvals_spec.rb
Seems that after Gitlab 13.12 MR /approvers endpoint was removed. 
(cant find endpoint in 13.12 https://docs.gitlab.com/13.12/ee/api/merge_request_approvals.html but was available in 13.10 - https://docs.gitlab.com/13.10/ee/api/merge_request_approvals.html#change-allowed-approvers-for-merge-request)
Added 3 new endpoints:
* Create merge request level rule (https://docs.gitlab.com/13.12/ee/api/merge_request_approvals.html#create-merge-request-level-rule)
* Update merge request level rule (https://docs.gitlab.com/13.12/ee/api/merge_request_approvals.html#update-merge-request-level-rule)
* Get merge request level rule (https://docs.gitlab.com/13.12/ee/api/merge_request_approvals.html#get-merge-request-level-rule)
* Delete merge request level rule …
> Add merge request level rule endpoints

- lib/gitlab/client/pipeline_schedules.rb
- spec/fixtures/pipeline_schedule_run.json
- spec/gitlab/client/pipeline_schedules_spec.rb
Closes https://github.com/NARKOZ/gitlab/issues/625
GitLab doc: https://docs.gitlab.com/ee/api/pipeline_schedules.html#run-a-scheduled-pipeline-immediately
> Add support for running a project pipeline schedule (#625)

- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
I've originally stumbled upon this issue after upgrading Gitlab server
from HTTP-only to HTTPS, but forgetting to update some scripts
which use gitlab cli. The cli behaved like everything is fine, but a
server has effectively become "read-only". I guess, I may be not the
only one bitten by this issue, so I've fixed it for everyone.
Citing the commit message:
> If HTTPS is enabled on a server, but the client uses plain HTTP
> Gitlab generates HTTP 301 redirect. By default HTTParty will
> follow with GET request regardless of the original method and
> any PUT/POST will silently fail to update the target. Fix by
> enabling HTTParty::maintain_method_across_redirects.
> Maintain methods across redirects

- lib/gitlab/client/merge_requests.rb
- spec/gitlab/client/merge_requests_spec.rb
I noticed the endpoint for merge request deletion did not exist.  I added it and added the test for it.
> Add an API endpoint for merge request deletion.

- lib/gitlab/error.rb
GitLab uses a CDN (Cloudflare), which can sometimes return a 522 error.
This PR adds an error class for HTTP status code 522.
> Raise error for HTTP status code 522

- lib/gitlab/error.rb
- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
Raise error for any 4xx or 5xx HTTP status code. If there is no special error class, raise `ResponseError`.
Fixes #639
> Raise error for any 4xx or 5xx HTTP status code

- lib/gitlab/client/groups.rb
- spec/gitlab/client/groups_spec.rb
As described in the [members endpoint](https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project): 
> Returns only direct members and not inherited members through ancestors groups.
This PR introduces [all members endpoint](https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-and-invited-members):
> [...] including inherited members, invited users, and permissions through ancestor groups.
> Add all group members endpoint

- lib/gitlab/client.rb
- lib/gitlab/client/packages.rb
- spec/fixtures/group_packages.json
- spec/fixtures/project_package.json
- spec/fixtures/project_package_files.json
- spec/fixtures/project_packages.json
- spec/gitlab/client/packages_spec.rb
This add a new `Packages` module that exposes methods to interact with the [GItLab Packages API](https://docs.gitlab.com/14.9/ee/api/packages.html)
- Implementation for all current endpoints exposed as part of the Packages API
- New spec file added plus dedicated stub content matching the example outputs from the GitLab docs
> Add Packages API implementation

- lib/gitlab/client/users.rb
- spec/gitlab/client/users_spec.rb
Gitlab 12.4 introduced activate and deactivate users feature. These two methods, viz. deactivate_user and activate_user, implement this capability available through the GitLab API.
> Added deactivate_user and activate_user methods

- lib/gitlab/client/merge_requests.rb
- spec/fixtures/merge_request_diffs.json
- spec/gitlab/client/merge_requests_spec.rb
["List merge request diffs"](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-request-diffs) appears to be missing from this gem, so this MR adds it. Thanks!
The fixture comes from the documentation.
Example usage:
```ruby
> Gitlab.merge_request_diffs(33727711, 1)
=> [#<Gitlab::ObjectifiedHash:2120 {hash: {"diff"=>"@@ -4,6 +4,10 @@ This README is intended to be helpful for colleagues at GitLab. For everything e\n \n Please `@` me in comments, issues, and MRs. I use TODOs, and rarely check notification emails. You can also DM me on Slack.\n \n+## My role\n+\n+I'm on the Application Security Team ([role description](https://about.gitlab.com/job-families/engineering/application-security/)) and you can find the teams I work with [on this handbook …
```
> Add the Merge Requests /diffs endpoint

- .github/workflows/ci.yml
- lib/gitlab/cli_helpers.rb
- lib/gitlab/client/issues.rb
- spec/fixtures/related_merge_requests.json
- spec/gitlab/client/issues_spec.rb
- Add related_merge_request Issue endpoint (https://docs.gitlab.com/ee/api/issues.html#list-merge-requests-related-to-issue)
- Fix outstanding rubocop issue
- Fix Actions; Ruby/Bundle version incompatibilities
```shell
$ rake rubocop
Offenses:
lib/gitlab/cli_helpers.rb:23:48: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a logical expression.
@client ||= Gitlab::Client.new(endpoint: (Gitlab.endpoint || ''))
^^^^^^^^^^^^^^^^^^^^^^^
165 files inspected, 1 offense detected, 1 offense autocorrectable
RuboCop failed!
```
> Add Issue related_merge_requests endpoint

- lib/gitlab/client/pipelines.rb
- spec/gitlab/client/pipelines_spec.rb
Adds support for the update pipeline metadata endpoint: https://docs.gitlab.com/ee/api/pipelines.html#update-pipeline-metadata:
```ruby
Gitlab.update_pipeline_metadata(5, 1, name: 'new name')
```
> Add pipeline metadata update endpoint

- lib/gitlab/client/pipelines.rb
- spec/fixtures/pipeline_variables.json
- spec/gitlab/client/pipelines_spec.rb
```ruby
Gitlab.pipeline_variables(12, 3)
```
https://docs.gitlab.com/ee/api/pipelines.html#get-variables-of-a-pipeline
Reopening #652
> Pipeline variables

- lib/gitlab/client.rb
- spec/gitlab/client_spec.rb
Prior this commit very short private tokens (< 4 chars) triggered: `ArgumentError: negative argument`
Also, if private token was a term which was part of the inspected string only the first occurrence was redacted.
https://gitlab.com/gitlab-org/quality/triage-ops/-/merge_requests/2919#note_1983270817
```
git checkout master -- lib
bundle exec rspec spec/gitlab/client_spec.rb
Randomized with seed 22140
Gitlab::Client
#inspect
with a known private token
is expected to include "@endpoint=" (FAILED - 1)
is expected to include "@private_token=\"****oint\"" (FAILED - 2)
with very short private token
example at ./spec/gitlab/client_spec.rb:33 (FAILED - 3)
with a private token
is expected to include "@private_token=\"******oken\""
with short private token
is expected to include …
```
> Redact short and known private tokens

- gitlab.gemspec
When using this Gem in Ruby 3.3.4 i'm getting this warning:
```
/builds/gitlab-community/meta/vendor/ruby/3.3.0/gems/gitlab-5.0.0/lib/gitlab/cli_helpers.rb:5: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of gitlab-5.0.0 to add base64 into its gemspec.
```
I noticed we can also see this in checks in this in checks like: https://github.com/NARKOZ/gitlab/actions/runs/10246689948/job/28344330836?pr=695#step:4:92
We can see this no longer appears in the checks for this PR: https://github.com/NARKOZ/gitlab/actions/runs/10390243537/job/28770239632?pr=697#step:4:93
> Add base64 to gemspec

- lib/gitlab/client/pipeline_schedules.rb
- spec/fixtures/pipeline_schedule_get_pipelines.json
- spec/gitlab/client/pipeline_schedules_spec.rb
GitLab pipeline now support getting all pipelines triggered by a pipeline schedule in a project
(https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-all-pipelines-triggered-by-a-pipeline-schedule).
```ruby
Gitlab.get_pipelines_by_pipeline_schedule(5, 3)
```
> Add get_pipelines_by_pipeline_schedule method

- lib/gitlab/configuration.rb
- lib/gitlab/request.rb
Closes: https://github.com/NARKOZ/gitlab/issues/668
Support specifying a prefix for personal access tokens and support using CI_JOB_TOKEN for authentication if the the token doesn't start with that prefix.
Ideally, we should default the prefix to `glpat-` so that it works out of the box. But that may break users on older GitLab instances where the prefix isn't present.
> Support using CI_JOB_TOKEN for authentication

- lib/gitlab/client/projects.rb
- spec/fixtures/project_access_token_create.json
- spec/fixtures/project_access_token_get.json
- spec/fixtures/project_access_tokens_get_all.json
- spec/gitlab/client/projects_spec.rb
Add the endpoints mentioned in https://docs.gitlab.com/ee/api/project_access_tokens.html
> Add Project Access Token related endpoints

- lib/gitlab/client/commits.rb
The `example` rdoc for the [create_commit](https://www.rubydoc.info/gems/gitlab/Gitlab%2FClient%2FCommits:create_commit) method should be indented and displayed a code block, however, it's currently rendering incorrectly with two `Gitlab.create_commit` method calls showing up as text on a single line:
This pull request adds indentation to fix this.
> Fix example rdoc comment for create_commit

- lib/gitlab/client/groups.rb
- spec/fixtures/group_member_override.json
- spec/gitlab/client/groups_spec.rb
Forwarding a suggestion by a GitLab customer to add this `post("/groups/#{url_encode team_id}/members/#{user_id}/override")` method, as it proved useful for custom scripting against a self-hosted GitLab server. I've added tests and a fixture, _greening_ `rspec` locally for me.
The [API endpoind is documented here](https://gitlab.com/gitlab-org/gitlab/-/blob/v18.1.1-ee/doc/api/members.md#set-override-flag-for-a-member-of-a-group).
> Add the set override flag API endpoint (of LDAP-sync'ed users)
