- lib/gitlab/client/notes.rb
- spec/gitlab/client/notes_spec.rb
Add `create_merge_request_note` to correspond to this API call:
https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/notes.md#create-new-merge-request-note
> Add create_merge_request_note

- lib/gitlab/client/notes.rb
> Added :page and :per_page query options for Notes methods

- lib/gitlab/api.rb
- lib/gitlab/cli.rb
- lib/gitlab/configuration.rb
- lib/gitlab/request.rb
- spec/gitlab/request_spec.rb
- spec/gitlab_spec.rb
This PR allows to authenticate via an oauth auth_token, should fix #104
> Authenticate via oauth an auth_token

- lib/gitlab/client/users.rb
- spec/gitlab/client/users_spec.rb
I needed a way to delete users, and it was not supported, so I've added it.
> Added Users#delete_user method

- lib/gitlab/client.rb
- lib/gitlab/client/builds.rb
- spec/fixtures/build.json
- spec/fixtures/build_cancel.json
- spec/fixtures/build_retry.json
- spec/fixtures/builds.json
- spec/fixtures/builds_commits.json
- spec/gitlab/client/builds_spec.rb
With Gitlab 8.4 new endpoint has been introduced for builds. This pull has the method calls and tests coverage for the new functionality.
> New builds endpoints

- lib/gitlab/client/groups.rb
Allow setting extra options such as per_page and page
> Make sure we allow passing options

- lib/gitlab/client/merge_requests.rb
- spec/gitlab/client/merge_requests_spec.rb
* add edit_merge_request_comment -> for editing a MR note 
* port from comments to newer 'notes' -> to get back the id
> add edit_merge_request_comment

- lib/gitlab/client/notes.rb
- spec/gitlab/client/notes_spec.rb
This covers listing merge request notes which was missing before.
> Support for listing merge request notes

- CHANGELOG.md
> Move share_project_with_group entry to Unreleased section

- lib/gitlab/client/merge_requests.rb
- spec/gitlab/client/merge_requests_spec.rb
Resolves https://github.com/NARKOZ/gitlab/issues/229
> Update merge_request endpoints to new merge_requests endpoints

- lib/gitlab/client.rb
- lib/gitlab/client/environments.rb
- spec/fixtures/environment.json
- spec/fixtures/environments.json
- spec/gitlab/client/environments_spec.rb
- spec/gitlab/client/groups_spec.rb
(to access new environments endpoints)
Fixes #285
> Add Environments module

- lib/gitlab/client.rb
- lib/gitlab/client/award_emojis.rb
- spec/fixtures/issue_award_emoji.json
- spec/fixtures/issue_award_emojis.json
- spec/fixtures/merge_request_award_emoji.json
- spec/fixtures/merge_request_award_emojis.json
- spec/fixtures/note_award_emoji.json
- spec/fixtures/note_award_emojis.json
- spec/fixtures/snippet_award_emoji.json
- spec/fixtures/snippet_award_emojis.json
- spec/gitlab/client/award_emojis_spec.rb
Methods to deal with the [Award Emoji API](http://docs.gitlab.com/ce/api/award_emoji.html)
* `award_emojis`: gets list of emojis for an awardable
* `note_award_emojis`: gets list of emojis for a note on an awardable
* `award_emoji`: gets a single emoji on an awardable
* `note_award_emoji`: gets a single emoji for a note on an awardable
* `create_award_emoji`: creates an emoji for an awardable
* `create_note_award_emoji`: creates an emoji for a note on an awardable
* `delete_award_emoji`: deletes an emoji from an awardable
* `delete_note_award_emoji`: deletes an emoji from a note on an awardable
> Award Emoji API

- lib/gitlab/client/branches.rb
- spec/gitlab/client/branches_spec.rb
to handle `developers_can_push` and `developers_can_merge` as described in Gitlab docs:
https://docs.gitlab.com/ce/api/branches.html#protect-repository-branch
> Update Branch docs and add options param to protect_branch

- lib/gitlab/client.rb
- lib/gitlab/client/boards.rb
- spec/fixtures/board_list.json
- spec/fixtures/board_lists.json
- spec/fixtures/boards.json
- spec/gitlab/client/boards_spec.rb
See https://docs.gitlab.com/ce/api/boards.html for documentation
> Add board api support

- lib/gitlab/cli_helpers.rb
> Verify object responds to :empty?

- lib/gitlab/client/branches.rb
- lib/gitlab/request.rb
- spec/gitlab/client/branches_spec.rb
This is related to issue #331, I needed to fix it for a project so if you like feel free to take it.
I also modified the tests but I am not an expert on rspec, maybe there is something you would like to adapt on that side. I have tried this and seems to be working for my use case.
> Implement new endpoint for protected branches

- lib/gitlab/client/merge_requests.rb
To avoid issues like the https://github.com/NARKOZ/gitlab/issues/323 this MR aims to improve the doc of create_merge_request command.
#hacktoberfest
> Add more details about options to create_merge_request doc

- lib/gitlab/client.rb
- lib/gitlab/client/deployments.rb
- spec/fixtures/deployment.json
- spec/fixtures/deployments.json
- spec/gitlab/client/deployments_spec.rb
Signed-off-by: Alex Ives <alex@ives.mn>
> Fixes #335: Added deployments api methods

- lib/gitlab/client/runners.rb
- spec/fixtures/runner_jobs.json
- spec/gitlab/client/runners_spec.rb
Add the possibility to list jobs for a specific runner.
> Add runner's jobs list API

- lib/gitlab/client/projects.rb
- spec/fixtures/user_projects.json
- spec/gitlab/client/projects_spec.rb
Add the possibility to obtain projects by user_id.
> Add user projects list API

- lib/gitlab/client/projects.rb
- spec/fixtures/project_forks.json
- spec/gitlab/client/projects_spec.rb
Refer: https://docs.gitlab.com/ce/api/projects.html#list-forks-of-a-project
> Add project forks list API

- lib/gitlab/client/merge_requests.rb
- spec/gitlab/client/merge_requests_spec.rb
> User Merge requests endpoint

- lib/gitlab/client/merge_requests.rb
- spec/fixtures/merge_request_discussion.json
- spec/fixtures/merge_request_discussion_note.json
- spec/fixtures/merge_request_discussions.json
- spec/gitlab/client/merge_requests_spec.rb
> Add merge request discussions API

- lib/gitlab/client/projects.rb
- spec/gitlab/client/projects_spec.rb
> Added .unshare_project_with_group to projects

- lib/gitlab/client/projects.rb
- spec/fixtures/project_key.json
- spec/fixtures/project_keys.json
- spec/gitlab/client/projects_spec.rb
> Allow to pass options for deploy keys

- lib/gitlab/client/projects.rb
> Fixed options for projects api v4 and updated docs

- lib/gitlab/client/projects.rb
- spec/fixtures/upload_file.json
- spec/gitlab/client/projects_spec.rb
> Add method to upload a file to a project

- lib/gitlab/client/users.rb
- spec/gitlab/client/users_spec.rb
This is a cleaned up version of pull request #314 which includes the requested changes:
- removed unrelated function
- added tests
> Ssh keys for different users

- lib/gitlab/client/events.rb
- spec/gitlab/client/events_spec.rb
> Fix project events path

- lib/gitlab/client/merge_requests.rb
Return should be an Array of ObjectifiedHash
Sorry for the previous rush PR
> Patch mr pipeline doc

- lib/gitlab/client.rb
- lib/gitlab/client/wikis.rb
- spec/fixtures/wiki.json
- spec/fixtures/wiki_attachment.json
- spec/fixtures/wikis.json
- spec/gitlab/client/wikis_spec.rb
Wikis API
`Gitlab.wikis(project)`
`Gitlab.wiki(project, slug)`
`Gitlab.create_wiki(project, title, content, options = {})`
`Gitlab.update_wiki(project, slug, options)`
`Gitlab.delete_wiki(project, slug)`
Closes #437
> Added wikis API

- lib/gitlab/client/branches.rb
- lib/gitlab/client/broadcast_messages.rb
- lib/gitlab/client/wikis.rb
Small fixes for doc mistakes in last few commits. Thanks @connorshea for pointing those out.
> Small doc fixes for last few commits

- lib/gitlab/client.rb
- lib/gitlab/client/protected_tags.rb
- spec/fixtures/protected_tag.json
- spec/fixtures/protected_tags.json
- spec/gitlab/client/protected_tags_spec.rb
**Protected tags API**:
```rb
Gitlab.protected_tags(project)
Gitlab.protected_tag(project, name)
Gitlab.protect_repository_tag(project, name)
Gitlab.unprotect_repository_tag(project, name)
```
closes #435
> Protected tags API

- lib/gitlab/client.rb
- lib/gitlab/client/repository_submodules.rb
- spec/gitlab/client/repository_submodules_spec.rb
Fix #449 
https://docs.gitlab.com/ce/api/repository_submodules.html
> Repository submodules API

- lib/gitlab/client.rb
- lib/gitlab/client/features.rb
- spec/fixtures/feature.json
- spec/fixtures/features.json
- spec/gitlab/client/features_spec.rb
```rb
Gitlab.features
Gitlab.set_feature(name, value, options = {})
Gitlab.delete_feature(name)
```
Closes #457
> Feature Flags API

- lib/gitlab/client.rb
- lib/gitlab/client/project_clusters.rb
- spec/fixtures/project_cluster.json
- spec/fixtures/project_clusters.json
- spec/gitlab/client/project_clusters_spec.rb
```ruby
Gitlab.project_clusters
Gitlab.project_cluster(project, cluster_id)
Gitlab.add_project_cluster(project, name, options = {})
Gitlab.edit_project_cluster(project, cluster_id, options = {})
Gitlab.delete_project_cluster(project, cluster_id)
```
Closes #456
> Project Clusters API

- lib/gitlab/client.rb
- lib/gitlab/client/group_boards.rb
- spec/fixtures/group_board.json
- spec/fixtures/group_board_list.json
- spec/fixtures/group_board_lists.json
- spec/fixtures/group_boards.json
- spec/fixtures/updated_group_board.json
- spec/gitlab/client/group_boards_spec.rb
- spec/gitlab/shell_spec.rb
```rb
Gitlab.group_boards(group)
Gitlab.group_board(group, id)
Gitlab.create_group_board(group, name)
Gitlab.edit_group_board(group, id, options = {})
Gitlab.delete_group_board(group, id)
Gitlab.group_board_lists(group, board_id)
Gitlab.group_board_list(group, board_id, id)
Gitlab.create_group_board_list(group, board_id, label_id)
Gitlab.edit_group_board_list(group, board_id, id, options = {})
Gitlab.delete_group_board_list(group, board_id, id)
```
Closes #467
> Group (Issue) Boards API

- lib/gitlab/client/merge_requests.rb
- spec/fixtures/participants.json
- spec/gitlab/client/merge_requests_spec.rb
```ruby
Gitlab.merge_request_participants(5, 36)
```
> add participants of merge request

- lib/gitlab/client.rb
- lib/gitlab/client/avatar.rb
- spec/fixtures/avatar.json
- spec/gitlab/client/avatar_spec.rb
Avatar API
```ruby
Gitlab.avatar(options = {})
```
Closes #470
> Avatar API

- lib/gitlab/client/groups.rb
- spec/fixtures/group_merge_requests.json
- spec/gitlab/client/groups_spec.rb
This is per issue https://github.com/NARKOZ/gitlab/issues/517
This adds the ability to see all merge requests for a group.
> Group merge requests

- lib/gitlab/client/users.rb
- spec/gitlab/client/projects_spec.rb
- spec/gitlab/client/users_spec.rb
> [FIX] Create user username argument fix

- lib/gitlab/client.rb
- lib/gitlab/client/issue_links.rb
- spec/fixtures/create_issue_link.json
- spec/fixtures/delete_issue_link.json
- spec/fixtures/project_issue_links.json
- spec/gitlab/client/issue_links_spec.rb
- spec/gitlab/shell_spec.rb
This is a continuation for #520 that fixes #519
> Tests for the issue_links methods

- lib/gitlab/client.rb
- lib/gitlab/client/issue_links.rb
address #519 
I've manually tested the implementation but didn't yet find the time to write the appropriate specs. If anyone wants to jump in and help, please be my guest 😃
> add issue link implementation

- lib/gitlab/client/build_variables.rb
Also update URIs for gitlab docs concerning group and project
build variables.
This addresses https://github.com/NARKOZ/gitlab/issues/527
> Allow for optional parameters to be passed into BuildVariables

- lib/gitlab/client/issues.rb
- spec/gitlab/client/issues_spec.rb
> Fix adding time spent with negative values

- lib/gitlab/client/projects.rb
- spec/fixtures/project_key_edit.json
- spec/gitlab/client/projects_spec.rb
This *should* work but I have no idea why rspec whines about my request stubs.
Closes #543
> Implement PUT /projects/:id/deploy_keys/:key_id

- lib/gitlab/client.rb
- lib/gitlab/client/epic_issues.rb
- lib/gitlab/client/notes.rb
- spec/fixtures/epic_issues.json
- spec/gitlab/client/epic_issues_spec.rb
- spec/gitlab/client/notes_spec.rb
Added two methods related to epics:
- #epic_notes: Fetch all the notes on an epic
- #create_epic_note: Add a note on an epic
- #epic_issues: Fetch all the issues for an epic
> Epics API: fetch and create epic notes + fetch epic issues

- lib/gitlab/client.rb
- lib/gitlab/client/user_snippets.rb
- spec/fixtures/created_user_snippet.json
- spec/fixtures/public_snippets.json
- spec/fixtures/snippet_user_agent_details.json
- spec/fixtures/updated_user_snippet.json
- spec/fixtures/user_snippet.json
- spec/fixtures/user_snippets.json
- spec/gitlab/client/merge_request_approvals_spec.rb
- spec/gitlab/client/user_snippets_spec.rb
Added support for user snippets from #552 
- user_snippets
- user_snippet
- user_snippet_raw
- create_user_snippet
- edit_user_snippet
- delete_user_snippet
- public_snippets
- snippet_user_agent_details
> Added support for user snippets API

- lib/gitlab/client/merge_requests.rb
Hi!
I just want to add some options to get merge request call.
Its pretty useful when you want to know number of commits behind the target branch.
Tell me what you think about it
> Add extra options for getting single merge request

- lib/gitlab/client/keys.rb
- spec/gitlab/client/keys_spec.rb
Hi, 
This feature is nice to have authenticating with a key.
Cheers,
Pim
> Feature find user/key by fingerprint

- lib/gitlab/client/users.rb
- spec/fixtures/impersonation_create.json
- spec/fixtures/impersonation_get.json
- spec/fixtures/impersonation_get_all.json
- spec/gitlab/client/users_spec.rb
Adds support for user impersonation tokens.
> user impersonation tokens

- lib/gitlab/client/merge_requests.rb
> Fix 404 error when retrieving the issues a merge_request will close

- lib/gitlab/client/project_releases.rb
- spec/gitlab/client/project_releases_spec.rb
```ruby
Gitlab.project_latest_release(3)
```
https://docs.gitlab.com/ee/api/releases/#get-the-latest-release
> Add Project's latest release

- lib/gitlab/client/container_registry.rb
- spec/gitlab/client/container_registry_spec.rb
Adds additional options to registry_repositories method
> Add additional options to registry repositories method
